osx_image: xcode10
language: objective-c

before_install:
  - bundle install
  - pod repo update
  - pod install

script:
  - set -o pipefail && xcodebuild -workspace Gray.xcworkspace -scheme "Gray" -sdk macosx clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO" | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
